### ISSUE TITLE
we could use pymzMl for reading mzML files

### ISSUE THREAD

**Issue by amnahsiddiqa** [shuzhao-li/asari#2]
pyopenms has to take care of memory leaks in their dev maintainence as it is python binding around C libraries of OpenMS (see e.g. https://github.com/OpenMS/OpenMS/pull/5390, https://github.com/OpenMS/OpenMS/pull/4488, https://github.com/OpenMS/OpenMS/blob/c2555c3278de34a5f261df9a0915f42a8bfada3c/src/openms/source/FORMAT/SqliteConnector.cpp , https://github.com/OpenMS/OpenMS/blob/d9692da0d410c06b6cdc960f608a5c962360d09c/src/openms/thirdparty/IsoSpec/IsoSpec/fixedEnvelopes.cpp) and its a common issue for such applications/tools (a pointer https://web.archive.org/web/20160316152429/http://www.lshift.net/blog/2008/11/14/tracing-python-memory-leaks/)

I happen to catch this through this warning; 
```
(base) MDG-JGM056:MetabolomicsData siddia$ python3 /Users/siddia/Desktop/MetabolomicsData/process_masstraces_mzlist_AS.py /Users/siddia/Desktop/MetabolomicsData/ConverttomzMl/MetaData-2/testchrom 
Determination of memory status is not supported on this 
 platform, measuring for memoryleaks will never fail
positive
Processed /Users/siddia/Desktop/MetabolomicsData/ConverttomzMl/MetaData-2/testchrom/MT_20210726_037_chrom.mzML to 7167 good massTraces..
negative
Processed /Users/siddia/Desktop/MetabolomicsData/ConverttomzMl/MetaData-2/testchrom/MT_20210726_036_chrom.mzML to 13321 good massTraces..
(base) MDG-JGM056:MetabolomicsData siddia$ 

```

I suggest to use pymzML (https://github.com/pymzml/pymzML) as we are right now using pyopenms only for reading our chromatogram mzML file and we can altogether avoid any complications if at all;

**Comment by shuzhao-li** [comment]
Implemented pymzml and multiprocessing in v 1.2
