### ISSUE TITLE
Asari skip all later samples with mzML processing error

### ISSUE THREAD

**Issue by gmhhope** [shuzhao-li/asari#28]
Asari run somehow skips all the later samples after certain files, suspecting this is due to memory shortage using the local computer to perform the run as the same run using HPC works.

```
mzML processing error in sample home/input/mzMLbyMethods/HILICpos_FS/pel_batch02_MT_20220909_093.mzML, skipped.
[Warning] Not index found and build_index_from_scratch is False
[Warning] Not index found and build_index_from_scratch is False
[Warning] Not index found and build_index_from_scratch is False
mzML processing error in sample home/input/mzMLbyMethods/HILICpos_FS/pel_batch03_MT_20220913_003.mzML, skipped.
[Warning] Not index found and build_index_from_scratch is False
[Warning] Not index found and build_index_from_scratch is False
[Warning] Not index found and build_index_from_scratch is False
...
```

- The log file using local computer: [asari_run_log_err_wt_multiSamples_skipped.md](https://github.com/shuzhao-li/asari/files/9780583/asari_run_log_err_wt_multiSamples_skipped.md)
- The log file using HPC: [AsariRun_HILICpos_FS_slurm-16416145.log](https://github.com/shuzhao-li/asari/files/9780600/AsariRun_HILICpos_FS_slurm-16416145.log)

There are significant uses of memory. @amnahsiddiqa what do you think?
```
Job ID: 16416145
Cluster: slurm_cluster
User/Group: root/jaxuser
State: COMPLETED (exit code 0)
Cores: 1
CPU Utilized: 02:22:22
CPU Efficiency: 96.24% of 02:27:56 core-walltime
Job Wall-clock time: 02:27:56
Memory Utilized: 8.15 GB
Memory Efficiency: 417.52% of 1.95 GB
```

**Comment by amnahsiddiqa** [comment]
For first thing, I see you are using docker in your local machine- Could you confirm me that it is the new docker that is compatible with your non M1 Mac that you created yourself as you mentioned https://github.com/shuzhao-li/asari/issues/27#issue-1406945616?  

For  second memory related question I see you are using default values for cores (single core per node) whereas asari by default uses 4 cores; you may need to change that in batch file.

**Comment by gmhhope** [comment]
@amnahsiddiqa The run was now smoothly run in sumner after the conversion in my computer.

I have changed the core numbers in the first place. But somehow it works for all modes now.
