### ISSUE TITLE
Scipy Error Due to Unordered Lists

### ISSUE THREAD

**Issue by obrien951** [shuzhao-li/asari#3]
Error with running asari on some in-house data. Screenshot of the error message below. It seems that the data is too big to upload.

(not shown) I printed out all the elements of the offending lists. All but the last elements of the list was ordered. I was able to get asari to run and to perform some peak picking and annotation by changing the following lines in `asari/algorithms.py`

from

```
292                spl = UnivariateSpline(xx, yy, )
293                SM.__rt_calibration__ = spl
294                SM.__rt_calibration__data__ = (xx, yy)
```
to
```
292                spl = UnivariateSpline(xx[:-1], yy, )
293                SM.__rt_calibration__ = spl
294                SM.__rt_calibration__data__ = (xx[:-1], yy)
```

![Screenshot from 2021-10-21 16-02-08](https://user-images.githubusercontent.com/28900775/138348916-a9c47623-64d5-4ca1-8c72-474060c8a08e.png)

version information:

Cloned with most recent commit:

02e56c922306a9f4e5e5358e361e163a20826c0f

uses

metDataModel : version 0.4.3
mass2chem: version 0.1.9
pyopenms: version 2.7.0
matplotlib: version 3.4.3
numpy: version 1.21.2
scipy: version 1.7.1
xlsxwriter: version

Conda environment managed by miniconda with conda 4.10.3
[JSOB_asari.zip](https://github.com/shuzhao-li/asari/files/7392499/JSOB_asari.zip)

**Comment by shuzhao-li** [comment]
Older version. max_rtime is automated now.
