### ISSUE TITLE
Remove __hacked_lowess__ in future version

### ISSUE THREAD

**Issue by shuzhao-li** [shuzhao-li/asari#30]
__hacked_lowess__ was used as a hack to fix bug in statsmodels.

statsmodels.nonparametric.smoothers_lowess, v 0.12, 0.13+
        https://www.statsmodels.org/stable/generated/statsmodels.nonparametric.smoothers_lowess.lowess.html    
        But xvals have to be forced as float array until the fix is in new release.

The fixed version is out now, but people may have older versions on their computers. We will wait a couple of asari releases before removing this function.

**Comment by jmmitc06** [comment]
There is now a check to ensure that a compatible version of statsmodels is present and if so, __hacked_lowes__ is not used. I'm going to save complete removal for a few versions at least.
