### ISSUE TITLE
Target extract seems to return only the first match in full feature table?

### ISSUE THREAD

**Issue by gmhhope** [shuzhao-li/asari#33]
`asari extract --target` function seems to only export the first instance of matched m/z, but not all?

#### The features of interest
![Screen Shot 2023-03-20 at 7 35 43 PM](https://user-images.githubusercontent.com/12982817/226488095-e9c23b33-a4ea-4c8f-9540-5ba226ce3f1e.png)
![Screen Shot 2023-03-20 at 7 39 14 PM](https://user-images.githubusercontent.com/12982817/226488522-1e406b54-eae1-4310-a605-d572ddb074ad.png)

#### The target extracted table
![Screen Shot 2023-03-20 at 7 37 24 PM](https://user-images.githubusercontent.com/12982817/226488296-191f416a-8cb5-4968-8e99-93d87708bd76.png)
- Only the first feature F13468 was captured but not others, though F1368-13470 all shares the same m/z and within the same mass track

**Comment by gmhhope** [comment]
### Kiupu thought it was a HCOOH addcut?
```
"kp2471_789.5309": {
    "interim_id": "kp2471_789.5309",
    "neutral_formula_mass": 789.530893176975,
    "neutral_formula": null,
    "Database_referred": [],
    "identity": [],
    "MS1_pseudo_Spectra": [
      {
        "apex": 1406,
        "peak_area": 944043,
        "height": 223864,
        "left_base": 1401,
        "right_base": 1408,
        "goodness_fitting": 0.6071372603094572,
        "cSelectivity": 0.5319148936170213,
        "parent_masstrack_id": 6093,
        "mz": 789.5270080566406,
        "snr": 8,
        "id_number": "F13409",
        "rtime": 307.9110878230002,
        "rtime_left_base": 306.8813713750002,
        "rtime_right_base": 308.32527462300004,
        "representative_intensity": 944043,
        "id": "F13409",
        "isotope": "13C/12C",
        "modification": "M-H-",
        "ion_relation": "13C/12C,M-H-",
        "parent_epd_id": "kp2471_789.5309"
      },
      {
        "apex": 1407,
        "peak_area": 755336636,
        "height": 40651380,
        "left_base": 1397,
        "right_base": 1419,
        "goodness_fitting": 0.8997672818688478,
        "cSelectivity": 0.8695652173913043,
        "parent_masstrack_id": 6750,
        "mz": 834.5291900634766,
        "snr": 67,
        "id_number": "F13470",
        "rtime": 308.1190798069998,
        "rtime_left_base": 306.0562757110002,
        "rtime_right_base": 310.640970783,
        "representative_intensity": 755336636,
        "id": "F13470",
        "isotope": "M0",
        "modification": "HCOOH",
        "ion_relation": "M0,HCOOH",
        "parent_epd_id": "kp2471_789.5309"
      },
```

**Comment by shuzhao-li** [comment]
Fixed in v 1.11.
Updated Docker image too.

**Comment by gmhhope** [comment]
![Screen Shot 2023-03-24 at 12 54 46 PM](https://user-images.githubusercontent.com/12982817/227590615-cf61d85d-8887-4b19-99f6-9b5013d26e95.png)

![Screen Shot 2023-03-24 at 12 55 43 PM](https://user-images.githubusercontent.com/12982817/227590810-d432f654-605f-403f-8ffe-baebd4e42e60.png)


{
        "apex": 1369,
        "peak_area": 228190463,
        "height": 15533247,
        "left_base": 1357,
        "right_base": 1380,
        "goodness_fitting": 0.9660354337568658,
        "cSelectivity": 1.0,
        "parent_masstrack_id": 6077,
        "mz": 788.5237426757812,
        "snr": 1080,
        "id_number": "F13346",
        "rtime": 300.2724246220002,
        "rtime_left_base": 297.6799482229998,
        "rtime_right_base": 302.5477387039998,
        "representative_intensity": 228190463,
        "id": "F13346",
        "isotope": "M0",
        "modification": "M-H-",
        "ion_relation": "M0,M-H-",
        "parent_epd_id": "kp2139_789.531"
      },

**Comment by gmhhope** [comment]
Similar PS that was assigned as HCOOH adduct:

<img width="1016" alt="Screen Shot 2023-03-24 at 12 58 04 PM" src="https://user-images.githubusercontent.com/12982817/227591372-fa9d557b-0eba-4533-bf48-730d0636d1f9.png">
