### ISSUE TITLE
Processing Nano-LC Data Very Slow

### ISSUE THREAD

**Issue by jmmitc06** [shuzhao-li/asari#39]
I have left identical jobs, processing a subset of nano-LC data with 25 experiments, running overnight on both my laptop and sumner (128G of ram) and neither have finished. 

In both cases, I see that in the /pickle/ subdirectory there are a number of pickle files but less than the number of acquisitions. I see messages showing that some samples have been extracted to mass tracks and the "Not index found" warnings from mzML, so my guess is that sample processing is at the single_sample_EICs_ step.

I have increased the min_peak_height to 1e6, I increased the multicore count to 12 for Sumner as this is a portion of the code that uses multiprocessing, but no noticeable improvement. 

At least one extraction failed (a solvent blank) on Sumner so far, but not sure why without more investigating. It did appear to be extracted fine locally, possibly related?

Any other suggestions? or do I just need to wait longer?

**Comment by jmmitc06** [comment]
I believe I have isolated the issue to bin_to_mass_tracks, probably due to build_chromatogram_by_mz_clustering. In blank2, a sample that takes a very long time, there are many calls to build_chromatogram_by_mz_clustering which seems to be the more expensive calculation. Increasing the mz tolerance could help but would come with other issues.

**Comment by shuzhao-li** [comment]
This may not be a Nano issue but derivatization issue. Yes, current mass track construction could have trouble with very 'dense' m/z distribution.

**Comment by jmmitc06** [comment]
Possibly supporting the above hypothesis, the unlabelled derivatized experimental samples processed very quickly while the 13C labeled pooled samples 2 of 3 finished in ~20 minutes, the other took 4 hours. I assume that labeling makes the m/z distribution more dense so I think that is what is going on here. I'll think of a solution.

**Comment by jmmitc06** [comment]
Going to close this and open a more descriptive issue. There is nothing specific to the nano-LC that needs fixing, we just need to better handle m/z dense regions in build_chromatogram_by_mz_clustering.
