### ISSUE TITLE
Alignment warning

### ISSUE THREAD

**Issue by xulei99** [shuzhao-li/asari#44]
Hello there, there is this warning sometimes, what should I do about this?
Pos_477C
    ~warning~ Faluire in retention time alignment (0); Pos_477C is used without alignment.

I found within the preferred_Feature_table, there are some peaks may be duplicates based on ppm<5, rt<6s), and some of them are from the same composite mass track while some are not. Is this normal?

**Comment by jmmitc06** [comment]
Hi, I know that we discussed this on email, but we too have encountered this problem and it is not "normal" behavior.

The retention time alignment selects a reference sample based on the number of anchor peaks in the sample. The sample with the most anchors is the reference. If a sample differs significantly from the selected reference i.e., there is poor correspondence between the sample's anchor peaks and the reference sample's anchor peaks, it will fail to align. This can cause a variety of issues including the duplicate 'split' peaks you are describing. 

Without the dataset, its hard to say exactly what the problem would be. A quick suggestion is to check the output from `asari process` and see what file was selected as the reference. Is it a "reasonable" selection, not a blank or standards, etc.?

**Comment by jmmitc06** [comment]
I'm going to close this issue since I believe your main question has been answered. We will be working on improving the alignment as part of resolving issue #49.
