### ISSUE TITLE
Retention Time Alignment Poorly Regularized Under Some Conditions

### ISSUE THREAD

**Issue by jmmitc06** [shuzhao-li/asari#49]
Here is the retention time alignment plot from a recent experiment (RP - pellets, Morphic): 

<img width="782" alt="Screenshot 2023-06-08 at 4 44 37 PM" src="https://github.com/shuzhao-li/asari/assets/10132705/027a60aa-a6f2-4c1d-9a21-ba201d4597c5">

And another with HILIC+ pellets:

<img width="703" alt="Screenshot 2023-06-08 at 3 14 50 PM" src="https://github.com/shuzhao-li/asari/assets/10132705/a5f271c8-e537-43e8-ab43-88ab04d681ca">

Most of the zig-zaggy chaotic regression lines are blanks, but it occassionally with 'real' samples as well. Suspect peak density is a factor here. Unclear if this has a major impact on results or not, especially with filtering.

**Comment by jmmitc06** [comment]
Some initial thoughts: 

- the anchoring at the beginning and end of the chromatograms does prevent "blowing up" but also a more regularized model should not have this problem anyways.
- I'm surprised we get the zig-zag behavior with lowess, need to find some examples and investigate further. Maybe some sets of peaks are shifted more severely while the overall chromatogram is shifted less. If that occurs, there is not an easy fix. 
- I think it is unlikely but maybe the rules for selecting anchors are not strict enough and we are picking up noise sometimes and aligning junk peaks in some samples. 
- Currently the criteria for selecting reference peaks considers m-selectivity but I did not see an explicit check on c-selectivity. Maybe we need both. 

@amnahsiddiqa, if you have ideas for better options than LOWESS, I would like to discuss with you. It would be my 'go-to' method as well but maybe if we put our heads together we can think of something.

**Comment by shuzhao-li** [comment]
Were the plots based on chromatograms.rt_lowess_calibration_debug or different code? 

The RT mapping dictionaries only record values that differ btw two samples. I think  rt_lowess_calibration_debug does the right plot.

**Comment by jmmitc06** [comment]
This issue, while not completely solved, has been partially mitigated by adding a threshold on max RT delta between peaks for alignment and by adding the option to do multiple lowess iterations. The first prevents severe outliers while multiple iterations does improve regularization. 

Alignment of blanks remains problematic but likely has no easy solution at this time. 

When misalignments occur, the solution so far has been to select a reference manually. Future efforts could seek to improve reference selection. A better algorithm, such as RANSAC, may be a future option also.
