### ISSUE TITLE
Support chained experiments linked by common samples

### ISSUE THREAD

**Issue by jmmitc06** [shuzhao-li/asari#53]
As discussed with Stephen Barnes.

For example xpresss and mpress samples.

**Comment by shuzhao-li** [comment]
I should include this in the implementation of `join` subcommand.

**Comment by jmmitc06** [comment]
In essence this is achieved by selecting references manually within each batch prior to joining. This could be made more explicit in the future.

**Comment by jmmitc06** [comment]
With [implement_join 3dc7ebe] pulled, this is comes down to selecting the appropriate references manually while peak picking each experiment. Will close.
