### ISSUE TITLE
How to pick reference sample for alignment ?

### ISSUE THREAD

**Issue by amnahsiddiqa** [shuzhao-li/asari#58]
For regular (underivitized) metabolomics data set that I analyzed recently (attached some qc), a blank sample is picked up as reference sample.  It would be helpful if we could use say like have top ten samples with highest landmarks peaks to choose from, our next reference or in some way skip the samples that user don't want to  use as reference sample like blanks.
[rpneg_share.zip](https://github.com/shuzhao-li/asari/files/12172409/rpneg_share.zip)

**Comment by jmmitc06** [comment]
Thanks, that's a good suggestion. I think that we need two enhancements here: 

The first is to display the list of possible reference samples using the existing criteria (num landmark peaks). The second is an option to provide a list of files that cannot be used as the reference. This should allow automated and semi-automated processing. These are both on my to do list. 

Big picture question though is why do blanks get selected for alignment and does it result in issues downstream? Aligning on the blanks could be aligning samples using common background ions which may still yield a good alignment.

**Comment by amnahsiddiqa** [comment]
@jmmitc06 : Yes as we discussed before that if blank is being picked it definitely have landmark peaks which should be able to be resolved but then I have not gone in details why there is trouble in rt alignment(I will do some query  plots later in day), but I have appended quick regular qc results which definitely demonstrate that there are problems in retention time alignment. 

Also it would be nice to have a label  "feature request". Since, you can keep feature enhancement for your own records but other people may request it, which you can approve or not.

**Comment by jmmitc06** [comment]
This has been implemented as of: [implement_join 846133a]. 

By default, the old behavior occurs where the sample with the largest number of anchor pairs is selected as the reference without user input. If you now pass the parameter '-f manual' you will get a terminal menu where you will have a list of sample names and the number of anchors. You can then select which one to use. You can still specify a sample by name using '-f <sample_name>' as previously too. 

The way to specify the selection in the menu is pretty ugly but did not require any additional dependencies. This will be cleaner in the GUI. Currently the entire list of samples is printed to the terminal which may be problematic.

This is not in the main branch yet, but will be pushed there soonish.

**Comment by jmmitc06** [comment]
I'm going to close this issue if this seems like a good resolution for you?

**Comment by amnahsiddiqa** [comment]
Thanks that works.
