### ISSUE TITLE
To add options to use txt/json for input parameters and workflows

### ISSUE THREAD

**Issue by shuzhao-li** [shuzhao-li/asari#6]

**Comment by amnahsiddiqa** [comment]
including input of txt file of filenames (mzML) other than directory

**Comment by shuzhao-li** [comment]
added support of user supplied parameters.yaml.

To feed a specific list of files should be part of scripting using asari, but not as a subcommand.
This is easy to do by replacing 
`list_input_files = read_project_dir(args.input)`.
Otherwise, a dedicated subcommand opens up many potential problems.
