### ISSUE TITLE
Prefered Feature table have features with all samples having 0s and no column regarding samples with peaks detected

### ISSUE THREAD

**Issue by amnahsiddiqa** [shuzhao-li/asari#9]
- before we had that metadata column included for sample number with peaks but now I can't see it ; we need to include that for easier data manipulation 
- Prefered feature table is still having the features with all missing values

**Comment by shuzhao-li** [comment]
In a few cases, a peak is detected in composite mass track (artificially) but individual samples don't have sufficient signal.
Added export filter on this. 
Fixed both issues.
